### ISSUE TITLE
How to change "Choose File" on file type input??

### ISSUE THREAD

**Issue by yudha062** [adamwathan/bootforms#138]
Please help me to change text "Choose File "on file type input button???
If possible, how do I change its shape ???

**Comment by adamwathan** [comment]
This is way outside the scope of the package and actually sort of a pain in the ass, see here:

https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/

If you want to do this sort of customization, you'd have to do it by hand instead of relying on this package to generate it.
