### ISSUE TITLE
Placing submit and cancel button in one group

### ISSUE THREAD

**Issue by blonkm** [adamwathan/bootforms#60]
Perhaps someone can tell me if there is an easier way to get submit and cancel buttons next to each other? The submit button goes in a group, so if there is a way to add the cancel button too in the same group that would solve this.

I am using this now, for lack of better:

```php
  {!! Form::submit('Update', array('class' => 'btn btn-info')) !!}
  {!! link_to_route('clubs.index', 'Cancel', null, array('class' => 'btn')) !!}
```

**Comment by adamwathan** [comment]
I would write the markup manually honestly. The biggest benefit of this package is saving you all the boilerplate with adding classes to the `help-block` paragraph tags for each form input and all that jazz so you get nice Bootstrap error styling in one line.

Buttons don't really get any of those benefits since they look the same no matter what the state of the form is, so I'd just do:

```
<div class="form-group">
    <a href="{{ route('clubs.index') }}" class="btn btn-default">Cancel</a>
    <button type="submit" class="btn btn-info">Update</button>
</div>
```

**Comment by blonkm** [comment]
OK, got it. Even without the form-group the buttons are side by side, so it's fine I guess.
