### ISSUE TITLE
Grouping Fields 

### ISSUE THREAD

**Issue by daPhantom** [adamwathan/bootforms#69]
Hey,

I read a lot of issues asking this but all were closed in the end.

Is there a way of grouping fields inside a div container? It's really hard to align fields next to each other in case you are using a horizontal form for example without any support for grouping which is crucial for bootstrap forms...

Basically this: http://stackoverflow.com/questions/12201835/form-inline-inside-a-form-horizontal-in-twitter-bootstrap

**Comment by adamwathan** [comment]
No plans to bake anything like this into the package. It's really meant just to speed up quick prototyping stuff where you aren't trying to make your forms look at all fancy.

If you need anything different than what comes out of the box, you're really way better off just writing the markup instead of using the package :+1:
